### PR TITLE
Added 90 second timer and changed the timer to be three equal segments, 1/3 of the timer pie each.

### PR DESCRIPTION
**Pull request by gleehokie**

### CODE REVIEW

**Comment by adrienjoly** [comment]
@gleehokie Thanks for your contribution!
Are you using it often?

**Comment by gleehokie** [comment]
Hi Adrien, I use it for our daily scrums/stand-ups.  We have a big team (15
people) and it helps to keep us on track.  I don't know Javascript, but I
could figure out how to add the 90 sec button.  :-)

One suggestion for you is to change the Application type to be an extension
instead of a main application.  That way the buttons appear to the right
side of the hangout window instead of taking the whole screen.  I have my
dev instance of the hangout-timer setup that way and it is more useable
since you don't need to switch back and forth to start the timer each time
a new person starts talking in the scrum.

[image: Inline image 1]

Also, I see one bug which is that the small timer circle stays on the video
even when you hit stop.  I think it is because it is not properly cleared,
but my lack of Javascript knowledge is preventing me from figuring it out.

Do you use the hangout-timer much?  I do notice that sometimes it doesn't
work at all.  When you click on the gadget icon the buttons appear, but
when you click a button the timer does not appear.  This might be due to a
problem Google has with Hangouts, but since the gadget is mostly JS that
might not be true.

Thanks for open sourcing this tool, it helps us a lot!

Greg

**Comment by adrienjoly** [comment]
Hi Greg,

Thanks for your reply! And congrats for having been able to figure out how to scratch your itch in javascript! :-)

I'm very glad to read that the extension is useful to you. I used to use it that way too, but now I'm working alone so I don't use it anymore.

To quickly answer one of your questions: I think that making an "extension" instead of "application" would not make the timer appear on other people's screens.

May I suggest that you post each feature request and bug in a separate Github Issue, please?
So that I can reply to each of them separately, and maybe other developers would like to tackle on of these problems.

Thanks again for contributing! :-)

**Comment by gleehokie** [comment]
Hi Adrien, I'd be happy to create the issues, but the issues tab is turned
on on the hangouts-timer repo.  Since you own the repo you can turn it on
in the settings.

Greg

**Comment by adrienjoly** [comment]
Oops, sorry about that...

I just turned the Issues tab back on :-)

Thanks, Greg!

**Pull request merged**
